# Survival Analyses (AML dataset)
# Bulk: pAML from TARGET (n=256)
# SC: 6 pAML from BCM/TCH inclusing Diagnosis and relapes timepoints (n=12)

# Load libraries:
library(survival)
library(survminer)

### Read TARGET patients Bulk count data:
TARGET <- read.csv("./AML.TARGET.Bulk.Count_Gene_expr_Just_Diagosis_No21_110320.csv")
rownames(TARGET) <- TARGET$X; TARGET=TARGET[,-1]

## Read TARGET patients clinical data:
clinical.dt <- read.delim("./AML-TARGET-RNAseq-Diagn-No_21-Anno-091920.txt")

## Read the predicted proportional results (LogNormalize-LogNormalize normalization) generated by deconvolution methods:
pJanus <- read.csv("./TARGET_AML_LogNormalize_LogNormalize_p.ft.csv")

# Extract patients IDs
TARGET.USI <- strsplit(pJanus$X, "[.]")
TARGET.USI <- matrix(unlist(TARGET.USI), ncol=5, byrow=TRUE)
TARGET.USI <- as.data.frame(TARGET.USI)
pJanus <- cbind.data.frame(TARGET.USI, pJanus)
pJanus <- pJanus[,-c(1,2,4,5,6)]
colnames(pJanus)[1] <- "TARGET.USI"

# Merge the cluster.prop variables to clinical data (Relapsed_died + non_Relapsed_Alive patients) n=181
merged.tAML <- merge(clinical.dt, pJanus, by="TARGET.USI")
merged.tAML.R.DoD <- merged.tAML[merged.tAML$First.Event=="Relapse" & merged.tAML$Vital.Status=="Dead",]   # 93
merged.tAML.C.Ali <- merged.tAML[merged.tAML$First.Event=="Censored" & merged.tAML$Vital.Status=="Alive",] # 88
t.AML.R.C.DOD.ALI <- rbind(merged.tAML.R.DoD,merged.tAML.C.Ali)

# Categorize the patients based on their median cut-off on cluster proportion (i. e. cluster 11): 
data=t.AML.R.C.DOD.ALI
cluster="cluster.11"
for(i in 1:(nrow(data))) {
  if(data[i,cluster] >= median(data[,cluster])) {
    data$cluster.11.pro[i] <- "high"
  } else {
    data$cluster.11.pro[i] <- "low"
  }
}

# Getting the status value
status <- c()
for(j in 1:nrow(data)) {
  if(data$Vital.Status[j]=="Dead") {
    status[j] <- 1
  } else {
    status[j] <- 0 
  } 
}

# Model overall survival
sfit <- survfit(Surv(Overall.Survival.Time.in.Days, status)~cluster.11.pro, data=data)
ggsurvplot(sfit, data = data, pval=T, risk.table = F, palette = c("red","blue"))

# Using cox ph regression to fit the model 
cfit <- coxph(Surv(Overall.Survival.Time.in.Days, status)~cluster.11, data= data)
cfit

# Model event-free survival
sfit0 <- survfit(Surv(Event.Free.Survival.Time.in.Days, status)~cluster.11.pro, data = data)
ggsurvplot(sfit0, data = data, pval=T, risk.table = F, palette = c("red","blue"))
# Using cox ph regression to fit the model 
cfit0 <- coxph(Surv(Event.Free.Survival.Time.in.Days, status)~cluster.11, data=data)
cfit0